name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    name: Frontend - Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - run: npm ci
      - run: npm run lint
      - run: npm run build

  backend:
    name: Backend - Lint & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: 'backend/package-lock.json'
      - run: npm ci
      - run: npx prisma generate --schema=prisma/schema.prisma
      - run: npm run lint
      - run: npm run build

  pruebas:
    name: Pruebas unitarias y cobertura
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm ci --prefix backend
      - name: Generar cliente de Prisma
        working-directory: ./backend
        run: npx prisma generate --schema=prisma/schema.prisma
      - run: npx vitest run --coverage

  e2e:
    name: Pruebas E2E
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: taskmanager
        ports: ['5432:5432']
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/taskmanager?schema=public
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm ci --prefix backend
      - name: Generar cliente de Prisma
        working-directory: ./backend
        run: npx prisma generate --schema=prisma/schema.prisma
      - name: Migrar base de datos
        working-directory: ./backend
        run: npx prisma migrate deploy --schema=prisma/schema.prisma
      - run: npx playwright install --with-deps chromium
      - name: Start backend
        run: npm run dev --prefix backend &
      - run: npx wait-on http://localhost:3000
      - run: npx playwright test